### ISSUE TITLE
Hosting this on your own server/docker

### ISSUE THREAD

**Issue by IDmedia** [Fenton-Fenton-Fenton/alexa-tube#11]
I'm not very familiar with Node JS yet. Is there a way to host this in Docker yourself? I'm not too interested in giving Amazon my credit card information and I already have server that runs a couple of Python skills.

I've tried to just use "node index.js" but that gives me the following error:
```
root@ubuntu:/opt/alexa-tube# node index.js
/opt/alexa-tube/node_modules/dropbox-v2-api/src/dropbox-api.js:19
        (requestOpts, {requiresAuthHeader}, userOpts, config) => {
                      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/alexa-tube/node_modules/dropbox-v2-api/index.js:1:80)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by Fenton-Fenton-Fenton** [comment]
In principle this will run in docker, but I have no experience of doing so - I expect you will need to make considerable changes as the Alexa SDK generally assumes that it is running on AWS. Additonally the skill utilises a number of native node modules which will need to be rebuilt for the platform you are running

**Comment by jimmypc92** [comment]
@IDmedia 

I have succesfully hosted this with NodeJs on a vm running in Microsoft Azure. The important part is that Alexa just sends post requests to the NodeJs app, so express can be used with a listener for post requests to the '/' route. Its important to use HTTPS as well since Alexa skills require it.

I added the following code to the top of index.js

```

var express = require('express');
var bodyParser = require('body-parser');
var app = express();
var https = require('https');

var options = {
    pfx: fs.readFileSync('/certs/cert.pfx'),
    passphrase: 'password'
};

ffmpeg.setFfmpegPath("./node_modules/ffmpeg-binaries/bin/ffmpeg.exe");

//
// Initialize the Alexa SDK
var Alexa = require('alexa-sdk');

app.use(bodyParser.json());
```

Then the following code to the bottom of index.js

```

app.post('/', function(req, res) {

    //
    // Build the context manually, because Amazon Lambda is missing
    console.log("Request received");
    //console.dir(req);

    var context = {

        succeed: function (result) {

            console.log(result);

            res.json(result);
        },
        fail: function (error) {

            console.log(error);
        }
    };

    //
    // Delegate the request to the Alexa SDK and the declared intent-handlers
    var player = new alextube(req.body, context);
    player.handle();
});

var listener = https.createServer(options, app).listen(443, function () {

    console.log('Express HTTPS server listening on port ' + listener.address().port);
});
```

If self hosting alexa skills in nodejs is what you are looking for I can try to beef up my simple nodejs alexa host repository at https://github.com/jimmypc92/SelfHostAlexaSkillNodeJs
