### ISSUE TITLE
"There was a problem with the selected skills response"

### ISSUE THREAD

**Issue by AltOfCtrl** [Fenton-Fenton-Fenton/alexa-tube#19]
I've been receiving this message when I use the skill. I check in the drop box and the settings.js file updates but the audio doesn't.
Any fixes?

**Comment by theophys2005** [comment]
I've been running into the same issue and I have further comments: 

1. The issue seems to originate from Processing result returning undefined: 

`2018-03-24T00:09:37.463Z	(...) TypeError: Cannot read property 'length_seconds' of undefined
at /var/task/index.js:769:35
at /var/task/node_modules/ytdl-core/lib/info.js:172:25
at /var/task/node_modules/ytdl-core/lib/sig.js:31:9
at IncomingMessage.<anonymous> (/var/task/node_modules/miniget/lib/index.js:75:11)
at emitNone (events.js:91:20)
at IncomingMessage.emit (events.js:185:7)
at endReadableNT (_stream_readable.js:974:12)
at _combinedTickCallback (internal/process/next_tick.js:80:11)
at process._tickDomainCallback (internal/process/next_tick.js:128:9)`

so it is info in ytld-core returning undefined for some reason

2. The issue seems to be specifically related to music videos. Asking to play "random stuff" or something non-music related gets me past the error with duration_in_seconds returned (and then it runs into the other issue which seems to be ffmpeg related because charlie bit my finger somehow works fine -- encoder/filesize issue?

Summary: youtube seems to treat music vids a bit differently from other vids causing the properties parser to choke.
