### ISSUE TITLE
Dropbox error coming from the Lambda function

### ISSUE THREAD

**Issue by ohadbenita** [Fenton-Fenton-Fenton/alexa-tube#2]
Hi,

Following the guide on YouTube, I managed to create the Lambda function and corresponding Alexa skill
The thing is when invoking the Lambda function it exits with the following stack trace : 

2017-07-31T19:42:25.550Z	5f52c9c9-7628-11e7-a066-45edb89f9880	ReferenceError: nofunction is not defined
at /var/task/index.js:237:21
at dropbox (/var/task/index.js:1109:21)
at application/json (/var/task/node_modules/dropbox-v2-api/src/dropbox-api.js:108:17)
at Request._callback (/var/task/node_modules/dropbox-v2-api/src/dropbox-api.js:127:8)
at Request.self.callback (/var/task/node_modules/dropbox-v2-api/node_modules/request/request.js:198:22)
at emitTwo (events.js:106:13)
at Request.emit (events.js:191:7)
at Request.<anonymous> (/var/task/node_modules/dropbox-v2-api/node_modules/request/request.js:1035:10)
at emitOne (events.js:101:20)
at Request.emit (events.js:188:7)

**Comment by Fenton-Fenton-Fenton** [comment]
Hi - I think there are 2 issues here:-

1. The skill had an issue trying to load settings from Dropbox - was this the first time that you used the skill? Make sure that you have copied the Dropbox Token properly without any extra spaces

2. There is a bug in the code which stopped the skill from producing a correct error - I'll correct that

**Comment by Fenton-Fenton-Fenton** [comment]
From your other issue I am assuming that you sorted the initial problem with Dropbox causing an error. 
I have updated the skill to remove the bug that prevented this error from being handled gracefully.

Closing
